import { Router } from 'express';
import { authenticate } from '../../middlewares/auth.js';
import { ragController, summarizeController, generateQAController, multiDocController } from './rag.controller.js';
const router = Router();
router.use(authenticate);
router.post('/query', ragController);
router.post('/multi-query', multiDocController);
router.post('/summarize/:documentId', summarizeController);
router.post('/generate-qa/:documentId', generateQAController);
export default router;
