// migrations/004_create_chunks_embeddings.js
// ============================================================
// document_chunks — stores text chunks extracted from documents
// Each chunk has its embedding vector for semantic search.
//
// KEY DESIGN DECISIONS:
// 1. embedding is vector(1536) — matches text-embedding-3-small
// 2. HNSW index for Approximate Nearest Neighbor (ANN) search
//    - Much faster than exact search at scale
//    - Sub-100ms on 1M+ vectors
// 3. org_id on chunks enables tenant-scoped vector search
// ============================================================

export const up = async (pgm) => {
  pgm.createTable('document_chunks', {
    id: {
      type: 'uuid',
      primaryKey: true,
      default: pgm.func('gen_random_uuid()'),
    },
    document_id: {
      type: 'uuid',
      notNull: true,
      references: '"documents"',
      onDelete: 'CASCADE', // Delete chunks when document deleted
    },
    org_id: {
      type: 'uuid',
      notNull: true,
      references: '"organizations"',
      onDelete: 'CASCADE',
      // Denormalized here for query performance —
      // avoids JOIN to documents on every vector search
    },
    // The actual text content of this chunk
    content: {
      type: 'text',
      notNull: true,
    },
    // Position info
    chunk_index: {
      type: 'integer',
      notNull: true, // 0-based position within document
    },
    // Token counts for context window management
    token_count: {
      type: 'integer',
    },
    // Page number (for PDF citations)
    page_number: {
      type: 'integer',
    },
    // The vector embedding — 1536 dimensions for text-embedding-3-small
    // This is the column pgvector searches against
    embedding: {
      type: 'vector(1536)',
      // NULL until embedding is generated by worker
    },
    // For full-text search (hybrid search)
    content_tsv: {
      type: 'tsvector',
      // Populated by trigger below
    },
    created_at: {
      type: 'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
    },
  });

  // ── Indexes ───────────────────────────────────────────────

  // Standard indexes
  pgm.createIndex('document_chunks', 'document_id');
  pgm.createIndex('document_chunks', 'org_id');
  pgm.createIndex('document_chunks', ['org_id', 'document_id']);

  // HNSW vector index for Approximate Nearest Neighbor search
  await pgm.sql(
    `CREATE INDEX IF NOT EXISTS document_chunks_embedding_hnsw_idx
     ON document_chunks
     USING hnsw (embedding vector_cosine_ops)
     WITH (m = 16, ef_construction = 64)`
  );

  // GIN index for full-text search (tsvector column)
  await pgm.sql(
    `CREATE INDEX IF NOT EXISTS document_chunks_content_tsv_idx
     ON document_chunks
     USING gin(content_tsv)`
  );

  // Trigger function: auto-populate content_tsv on INSERT/UPDATE
  await pgm.sql(`
    CREATE OR REPLACE FUNCTION update_chunk_tsv()
    RETURNS trigger AS $$
    BEGIN
      NEW.content_tsv = to_tsvector('english', NEW.content);
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
  `);

  await pgm.sql(`
    CREATE OR REPLACE TRIGGER update_chunk_content_tsv
    BEFORE INSERT OR UPDATE ON document_chunks
    FOR EACH ROW EXECUTE FUNCTION update_chunk_tsv()
  `);
};

export const down = (pgm) => {
  pgm.dropTable('document_chunks', { cascade: true });
};
