import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  ChevronLeft, HelpCircle, Loader2, AlertCircle,
  Download, RefreshCw, BookOpen, Brain, Lightbulb, ChevronDown, ChevronUp, Sparkles
} from 'lucide-react';
import { searchApi } from '../api/search';
import { exportQAPdf } from '../utils/exportPdf';

const difficultyConfig = {
  easy:   { cls: 'bg-green-100 text-green-700 border-green-200 dark:bg-green-500/20 dark:text-green-400 dark:border-green-500/30', dot: 'bg-green-500' },
  medium: { cls: 'bg-yellow-100 text-yellow-700 border-yellow-200 dark:bg-yellow-500/20 dark:text-yellow-400 dark:border-yellow-500/30', dot: 'bg-yellow-500' },
  hard:   { cls: 'bg-red-100 text-red-700 border-red-200 dark:bg-red-500/20 dark:text-red-400 dark:border-red-500/30', dot: 'bg-red-500' },
};

const typeConfig = {
  factual:    { cls: 'bg-blue-100 text-blue-700 dark:bg-blue-500/20 dark:text-blue-400', icon: BookOpen },
  conceptual: { cls: 'bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-400', icon: Brain },
  analytical: { cls: 'bg-orange-100 text-orange-700 dark:bg-orange-500/20 dark:text-orange-400', icon: Lightbulb },
};

function QuestionCard({ qa, index }) {
  const [revealed, setRevealed] = useState(false);
  const diff = difficultyConfig[qa.difficulty] || difficultyConfig.medium;
  const type = typeConfig[qa.type] || typeConfig.factual;
  const TypeIcon = type.icon;

  return (
    <div className="bg-card border border-border rounded-2xl overflow-hidden hover:shadow-md transition-shadow">
      <div className="p-5 pb-4">
        <div className="flex items-start justify-between gap-3 mb-4">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold border ${diff.cls}`}>
              <span className={`w-1.5 h-1.5 rounded-full ${diff.dot}`}></span>
              {qa.difficulty}
            </span>
            <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${type.cls}`}>
              <TypeIcon size={11} />{qa.type}
            </span>
          </div>
          <span className="text-xs font-bold text-muted-foreground bg-secondary w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0">
            {index + 1}
          </span>
        </div>
        <p className="text-gray-900 dark:text-foreground font-semibold text-base leading-relaxed">{qa.question}</p>
      </div>
      <div className="border-t border-border">
        <button
          onClick={() => setRevealed(!revealed)}
          className="w-full flex items-center justify-between px-5 py-3 text-sm font-medium text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-500/10 transition-colors"
        >
          <span>{revealed ? 'Hide Answer' : 'Reveal Answer'}</span>
          {revealed ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </button>
        {revealed && (
          <div className="px-5 pb-5">
            <div className="bg-blue-50 dark:bg-blue-500/10 border border-blue-100 dark:border-blue-500/20 rounded-xl p-4">
              <p className="text-gray-700 dark:text-blue-100 text-sm leading-relaxed">{qa.answer}</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function QAGenerator() {
  const { documentId } = useParams();
  const navigate = useNavigate();
  const [allQuestions, setAllQuestions] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [count, setCount] = useState(10);
  const [generated, setGenerated] = useState(false);
  const [diffFilter, setDiffFilter] = useState('all');

  useEffect(() => {
    setAllQuestions([]);
    setGenerated(false);
    setError(null);
    setCount(10);
    setDiffFilter('all');
  }, [documentId]);

  const handleGenerate = async (questionCount = count) => {
    setIsGenerating(true);
    setError(null);
    setAllQuestions([]);
    setDiffFilter('all');
    try {
      const res = await searchApi.generateQA(documentId, questionCount);
      setAllQuestions(res.data.data.questions || []);
      setGenerated(true);
    } catch (err) {
      setError(err.response?.data?.message || err.message || 'Failed to generate Q&A');
      setGenerated(false);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExport = () => {
    if (!filteredQuestions.length) return;
    const content = `# Q&A Study Guide\nGenerated by DocMind AI\n\n${filteredQuestions.map((q, i) =>
      `## Q${i+1}: ${q.question}\n**Difficulty:** ${q.difficulty} | **Type:** ${q.type}\n\n**Answer:** ${q.answer}\n`
    ).join('\n---\n\n')}`;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = `qa-${documentId}.md`; a.click();
    URL.revokeObjectURL(url);
  };

  const stats = {
    easy: allQuestions.filter(q => q.difficulty === 'easy').length,
    medium: allQuestions.filter(q => q.difficulty === 'medium').length,
    hard: allQuestions.filter(q => q.difficulty === 'hard').length,
  };

  const filteredQuestions = diffFilter === 'all'
    ? allQuestions
    : allQuestions.filter(q => q.difficulty === diffFilter);

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      {/* Back */}
      <button onClick={() => navigate('/documents')}
        className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors text-sm">
        <ChevronLeft size={16} /> Back to Documents
      </button>

      {/* Header — matches Summarizer style */}
      <div className="bg-card border border-border rounded-xl p-6">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 bg-violet-500/20 rounded-xl flex items-center justify-center">
            <HelpCircle className="w-6 h-6 text-violet-500" />
          </div>
          <div>
            <h1 className="text-xl font-bold">Auto Q&A Generator</h1>
            <p className="text-muted-foreground text-sm">Generate study questions & answers using Groq Llama 3.3</p>
          </div>
        </div>
      </div>

      {/* Loading */}
      {isGenerating && (
        <div className="text-center py-16 bg-card border border-border rounded-xl">
          <Loader2 className="w-12 h-12 animate-spin text-violet-500 mx-auto mb-4" />
          <p className="text-lg font-semibold">Generating {count} questions...</p>
          <p className="text-muted-foreground text-sm mt-1">Groq AI is analyzing your document</p>
        </div>
      )}

      {/* Ready to Generate — clean professional UI */}
      {!generated && !isGenerating && (
        <div className="bg-card border border-border rounded-xl p-10 text-center">
          <div className="max-w-sm mx-auto">
            <div className="w-16 h-16 bg-violet-500/10 rounded-2xl flex items-center justify-center mx-auto mb-5">
              <Sparkles className="w-8 h-8 text-violet-500" />
            </div>
            <h2 className="text-xl font-bold mb-2">Ready to Generate</h2>
            <p className="text-muted-foreground text-sm mb-8 leading-relaxed">
              Instantly create smart questions with answers, difficulty levels, and type classifications from your document.
            </p>

            {error && (
              <div className="flex items-center gap-2 text-red-500 bg-red-500/10 border border-red-500/20 rounded-xl px-4 py-3 mb-6">
                <AlertCircle size={16} /><span className="text-sm">{error}</span>
              </div>
            )}

            {/* Quantity selector */}
            <div className="flex items-center justify-center gap-3 mb-8">
              <span className="text-sm font-medium text-muted-foreground">Questions:</span>
              {[5, 10, 15].map(n => (
                <button key={n} onClick={() => setCount(n)}
                  className={`w-12 h-12 rounded-xl text-sm font-bold transition-all border-2 ${
                    count === n
                      ? 'bg-violet-600 text-white border-violet-600 shadow-md'
                      : 'bg-secondary text-muted-foreground border-border hover:border-violet-400'
                  }`}>
                  {n}
                </button>
              ))}
            </div>

            <button onClick={() => handleGenerate(count)} disabled={isGenerating}
              className="w-full flex items-center justify-center gap-3 px-8 py-4 bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white font-bold text-base rounded-xl transition-all hover:shadow-lg">
              <HelpCircle className="w-5 h-5" />Generate {count} Questions
            </button>
          </div>
        </div>
      )}

      {/* Results */}
      {generated && !isGenerating && allQuestions.length > 0 && (
        <div className="space-y-6">

          {/* Stats + controls */}
          <div className="bg-card border border-border rounded-xl p-5">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-5">
                <div>
                  <p className="text-2xl font-bold">{allQuestions.length}</p>
                  <p className="text-xs text-muted-foreground">Total Questions</p>
                </div>
                <div className="flex items-center gap-3">
                  {stats.easy > 0 && <span className="flex items-center gap-1.5 text-sm font-medium text-green-600 dark:text-green-400"><span className="w-2 h-2 bg-green-500 rounded-full"></span>{stats.easy} easy</span>}
                  {stats.medium > 0 && <span className="flex items-center gap-1.5 text-sm font-medium text-yellow-600 dark:text-yellow-400"><span className="w-2 h-2 bg-yellow-500 rounded-full"></span>{stats.medium} medium</span>}
                  {stats.hard > 0 && <span className="flex items-center gap-1.5 text-sm font-medium text-red-600 dark:text-red-400"><span className="w-2 h-2 bg-red-500 rounded-full"></span>{stats.hard} hard</span>}
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button onClick={() => handleGenerate(count)}
                  className="flex items-center gap-2 px-3 py-2 bg-secondary hover:bg-secondary/80 text-sm font-medium rounded-lg transition-colors">
                  <RefreshCw size={13} />Regenerate
                </button>
                <button onClick={handleExport}
                  className="flex items-center gap-2 px-3 py-2 bg-violet-600 hover:bg-violet-500 text-white text-sm font-semibold rounded-lg transition-colors">
                  <Download size={13} />Export
                </button>
              </div>
            </div>
          </div>

          {/* Difficulty Filter */}
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-sm font-medium text-muted-foreground mr-1">Filter:</span>
            {[
              { key: 'all', label: `All (${allQuestions.length})`, cls: 'bg-primary text-primary-foreground', inactiveCls: 'bg-secondary text-muted-foreground hover:bg-secondary/80' },
              { key: 'easy', label: `Easy (${stats.easy})`, cls: 'bg-green-600 text-white', inactiveCls: 'bg-green-500/10 text-green-600 dark:text-green-400 border border-green-500/20 hover:bg-green-500/20' },
              { key: 'medium', label: `Medium (${stats.medium})`, cls: 'bg-yellow-500 text-white', inactiveCls: 'bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border border-yellow-500/20 hover:bg-yellow-500/20' },
              { key: 'hard', label: `Hard (${stats.hard})`, cls: 'bg-red-600 text-white', inactiveCls: 'bg-red-500/10 text-red-600 dark:text-red-400 border border-red-500/20 hover:bg-red-500/20' },
            ].map(f => (
              <button key={f.key} onClick={() => setDiffFilter(f.key)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${diffFilter === f.key ? f.cls : f.inactiveCls}`}>
                {f.label}
              </button>
            ))}

            <div className="ml-auto flex items-center gap-2">
              <span className="text-sm text-muted-foreground">More:</span>
              {[5, 10, 15].map(n => (
                <button key={n} onClick={() => { setCount(n); handleGenerate(n); }}
                  disabled={isGenerating}
                  className="px-3 py-1.5 bg-secondary hover:bg-secondary/80 text-muted-foreground text-xs font-medium rounded-lg transition-colors disabled:opacity-50">
                  {n}
                </button>
              ))}
            </div>
          </div>

          {/* Question Cards */}
          {filteredQuestions.length === 0 ? (
            <div className="text-center py-10 text-muted-foreground text-sm bg-card border border-border rounded-xl">
              No {diffFilter} questions in this set. Try regenerating.
            </div>
          ) : (
            <div className="grid gap-4">
              {filteredQuestions.map((qa, i) => (
                <QuestionCard key={`${documentId}-${diffFilter}-${i}`} qa={qa} index={i} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}